# http://doc.gitlab.com/ce/ci/yaml/README.html
# https://gitlab.com/rychly-edu/docker/docker-openwrt-sdk

# Fixed OpenWrt version to rebuild on its version updates
image: registry.gitlab.com/rychly-edu/docker/docker-openwrt-sdk:19.07.6-ath79

build:
  stage: build
  script:
    - export MAKEFLAGS="${MAKEFLAGS} OUTPUT_DIR=${CI_PROJECT_DIR}/bin -s"
    - /add-custom-local-feed.sh "${CI_PROJECT_DIR}"
    - /install-custom-feed-packages.sh
    - /reconfigure.sh
    - /make-custom-feed-packages.sh
    - /make-index.sh "${CI_PROJECT_DIR}/key-build"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - bin

pages:
  stage: deploy
  script:
    - mkdir -p ./public
    - /generate-repository.sh "${CI_PROJECT_DIR}/public" "${CI_PROJECT_DIR}/key-build.pub" "${CI_PROJECT_DIR}/bin"
    - mv LICENSE ./public/
    - ./generate-webpage.sh "${CI_PROJECT_DIR}/public" > ./public/index.html
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - bin
