# http://doc.gitlab.com/ce/ci/yaml/README.html
# https://gitlab.com/rychly-edu/docker/docker-openwrt-sdk

image: registry.gitlab.com/rychly-edu/docker/docker-openwrt-sdk:latest

before_script:
  - /add-custom-local-feed.sh "${CI_PROJECT_DIR}"

build:
  stage: build
  script:
    - export MAKEFLAGS="${MAKEFLAGS} -s"
    - /install-custom-feed-packages.sh
    - /reconfigure.sh
    - /make-custom-feed-packages.sh
    - /make-index.sh "${CI_PROJECT_DIR}/key-build"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - ${SDK_HOME}/bin

pages:
  stage: deploy
  script:
    - mkdir -p ./public
    - /generate-repository.sh "${CI_PROJECT_DIR}/public" "${CI_PROJECT_DIR}/key-build.pub"
    - ./generate-webpage.sh "${CI_PROJECT_DIR}/public" > ./public/index.html
  artifacts:
    paths:
      - public
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - ${SDK_HOME}/bin
