#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2014 OpenWrt.org

START=99
STOP=99

USE_PROCD=1

SERVICE_USER=network
SERVICE_UID=101
SERVICE_GROUP=network
SERVICE_GID=101

start_service() {
	# Set/edit this before starting service !!!
	CFGFILE=/etc/smsd.conf

	user_exists ${SERVICE_USER} ${SERVICE_UID} || user_add ${SERVICE_USER} ${SERVICE_UID} ${SERVICE_GID} /tmp
	group_exists ${SERVICE_GROUP} ${SERVICE_GID} || group_add ${SERVICE_GROUP} ${SERVICE_GID}

	for CFG in checked failed incoming outgoing phonecalls report saved sent stats; do
		LINE=$(grep -o "^${CFG} *= */.*\$" "${CFGFILE}")
		[ $? -eq 0 -a -n "${LINE}" ] && {
			DIR=$(echo "${LINE}" | sed "s/^${CFG} *= *\\(.*\\)\$/\\1/")
			[ -d "${DIR}" ] || {
				mkdir -m 0755 -p "${DIR}"
				chmod 0770 "${DIR}"
				chown "${SERVICE_UID}:${SERVICE_GID}" "${DIR}"
			}
		}
	done

	for CFG in infofile pidfile; do
		LINE=$(grep -o "^${CFG} *= */.*\$" "${CFGFILE}")
		[ $? -eq 0 -a -n "${LINE}" ] && {
			FILE=$(echo "${LINE}" | sed "s/^${CFG} *= *\\(.*\\)\$/\\1/")
			[ -f "${FILE}" ] || {
				touch "${FILE}"
				chmod 0660 "${FILE}"
				chown "${SERVICE_UID}:${SERVICE_GID}" "${FILE}"
			}
		}
	done

	procd_open_instance
	procd_set_param command /usr/bin/smsd "-c${CFGFILE}" -t "-u${SERVICE_USER}" "-g${SERVICE_GROUP}"
	procd_set_param env \
		LD_LIBRARY_PATH=/lib:/usr/lib \
		PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
	procd_close_instance
}
