--- a/Makefile	2014-07-10 23:34:39.312072380 +0200
+++ b/Makefile	2014-07-10 23:35:51.112070259 +0200
@@ -9,7 +9,7 @@
 version = 1.8
 
 SHELL = /bin/sh
-CXXFLAGS = -Wall -O2 -fomit-frame-pointer -pipe
+#CXXFLAGS = -Wall -O2 -fomit-frame-pointer -pipe
 INSTALL = install
 
 prefix = /usr/local
@@ -196,11 +196,11 @@
 
 $(installlibauxdir)/512bold: $(srcbindir)/512bold
 	$(INSTALL) -d $(dir $@)
-	$(INSTALL) -m755 -s $< $@
+	$(INSTALL) -m755    $< $@
 
 $(installlibauxdir)/512bold1: $(srcbindir)/512bold1
 	$(INSTALL) -d $(dir $@)
-	$(INSTALL) -m755 -s $< $@
+	$(INSTALL) -m755    $< $@
 
 ###############################################################################
 
@@ -335,9 +335,9 @@
 install: all
 	$(INSTALL) -d $(bindir) $(filtersdir) $(auxdir) $(libauxdir) \
 		$(develdir) $(libdeveldir) $(mydocdir) $(mandir)
-	$(INSTALL) -m755 -s $(installbindir)/trs     $(bindir)
+	$(INSTALL) -m755    $(installbindir)/trs     $(bindir)
 	$(INSTALL) -m755    $(installbindir)/konwert $(bindir)
-	$(INSTALL) -m755 -s $(installbindir)/filterm $(bindir)
+	$(INSTALL) -m755    $(installbindir)/filterm $(bindir)
 	cp -dRf $(installfiltersdir)/* $(filtersdir)
 	$(perl) $(srcdeveldir)/mkaliases $(srcdeveldir)/aliases \
 		$(installfiltersdir) $(filtersdir)
